### ISSUE TITLE
install default fails 

### ISSUE THREAD

**Issue by alexxa** [modularity-modules/java#1]
@KarstenHopp 

Problem 1: conflicting requests  - nothing provides xorg-x11-fonts-Type1 needed by java-1.8.0-openjdk-1:1.8.0.144-7.b01.module_e0ebd551.x86_64

Problem 2: package java-1.8.0-openjdk-devel-1:1.8.0.144-7.b01.module_e0ebd551.x86_64 requires java-1.8.0-openjdk(x86-64) = 1:1.8.0.144-7.b01.module_e0ebd551, but none of the providers can be installed  - conflicting requests  - nothing provides xorg-x11-fonts-Type1 needed by java-1.8.0-openjdk-1:1.8.0.144-7.b01.module_e0ebd551.x86_64

Problem 3: package java-1.8.0-openjdk-headless-1:1.8.0.144-7.b01.module_e0ebd551.x86_64 requires copy-jdk-configs >= 2.2, but none of the providers can be installed  - conflicting requests  - nothing provides lua-posix needed by copy-jdk-configs-3.3-1.module_e0ebd551.noarch

Problem 4: package javapackages-tools-5.0.0-9.module_e0ebd551.noarch requires java-1.8.0-openjdk-headless, but none of the providers can be installed  - package java-1.8.0-openjdk-headless-1:1.8.0.144-7.b01.module_e0ebd551.x86_64 requires copy-jdk-configs >= 2.2, but none of the providers can be installed  - conflicting requests  - nothing provides lua-posix needed by copy-jdk-configs-3.3-1.module_e0ebd551.noarch

**Comment by nphilipp** [comment]
As discussed, it's the `lua-posix` package that is missing.

**Comment by nphilipp** [comment]
ATM nothing except `copy-jdk-configs` seems to require `lua-posix` but I don't think that's guaranteed. For the time being, we might get away with putting it directly into java, though.

**Comment by KarstenHopp** [comment]
The latest java module already has lua-posix. the latest fonts module (built today) has a couple hundred fonts added, i.e. xorg-x11-fonts-Type1.
Please test again with tomorrows compose

**Comment by alexxa** [comment]
java installs fine in the latest Boltron-F27 20171028
